{{/*apiVersion: {{ .Values.apiVersion }}*/}}
kubernetesVersion: {{ .Values.kubernetesVersion }}
kind: ConfigMap
metadata:
  name: my-configmap
data:
  myValue: "Hello World"
  drink: {{ .Values.favoriteDrink }}
